title: Domingos de Eulária Dumba
description: Data Scientist & ML Engineer
url: "https://www.domingosdeeulariadumba.com"
baseurl: ""

markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: "TeX"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - TODO.md
  - .gitignore
  - .github

include:
  - scripts/
  - styles/